name: CI
on:
  - pull_request
  - push

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
          - latest-stable
          - edge
    steps:
      - name: Checkout alpine-make-rootfs repository
        uses: actions/checkout@v4
        with:
          repository: alpinelinux/alpine-make-rootfs

      - name: Build rootfs using script from stdin
        run: |
          sudo ./alpine-make-rootfs \
              --branch ${{ matrix.branch }} \
              --packages 'mimalloc' \
              --script-chroot \
              AlpineLinux_edge-$(date +%Y%m%d).tar.zst - <<'SHELL'
                      printf '\nLD_PRELOAD="/usr/lib/libmimalloc.so"\n' >> /etc/profile
                      echo "Check out [filesystems](https://github.com/xplshn/filesystems) for more information about this rootfs and its purpose" >> /etc/motd
          SHELL

      - name: Create Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          name: "Build ${{ env.RELEASE_TAG }}"
          tag_name: "${{ env.RELEASE_TAG }}"
          prerelease: false
          draft: false
          generate_release_notes: false
          make_latest: true
          files: |
            ${{ github.workspace }}/dist/*
