name: CI
on:
  - pull_request
  - push

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
          - latest-stable
          - edge
    steps:
      - name: Checkout alpine-make-rootfs repository
        uses: actions/checkout@v4
        with:
          repository: alpinelinux/alpine-make-rootfs

      - name: Set release tag
        id: set_tag
        run: echo "RDATE=$(date +%d-%m-%Y)" >> $GITHUB_ENV

      - name: Build rootfs using script from stdin
        run: |
          mkdir -p "${{ github.workspace }}/dist"
          sudo "${{ github.workspace }}/alpine-make-rootfs" \
              --branch ${{ matrix.branch }} \
              --packages 'mimalloc' \
              --script-chroot \
              "${{ github.workspace }}/dist/AlpineLinux_edge-$(uname -m).tar.zst" - <<'SHELL'
                      printf '\nLD_PRELOAD="/usr/lib/libmimalloc.so"\n' >> /etc/profile
                      echo "Check out [filesystems](https://github.com/xplshn/filesystems) for more information about this rootfs and its purpose" >> /etc/motd
          SHELL
          ls "${{ github.workspace }}/dist"

      - name: Create Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          name: "${{ env.RDATE }}"
          tag_name: "${{ env.RDATE }}"
          prerelease: false
          draft: false
          generate_release_notes: false
          make_latest: true
          files: |
            ${{ github.workspace }}/dist/*.tar*
